name: CRI-O HTTP server test

concurrency:
  group: crio-server-${{ github.head_ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 */1 * *"

jobs:
  crio_server:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "WasmEdge latest release, Crun master"
            latest: true
            wasmedge: ""
            crun: ""
            zh: "FALSE"
            tag: "latest"
            config: "container_http_server.json"
          - name: "WasmEdge 0.9.1, Crun 1.4.5"
            latest: false
            wasmedge: "0.9.1"
            crun: "1.4.5"
            zh: "FALSE"
            tag: "compat"
            config: "container_http_server_compat.json"
          - name: "WasmEdge 0.10.0, Crun 1.5"
            latest: false
            wasmedge: "0.10.0"
            crun: "1.5"
            zh: "FALSE"
            tag: "latest"
            config: "container_http_server.json"
          - name: "WasmEdge latest release, Crun master, ZH"
            latest: true
            wasmedge: ""
            crun: ""
            zh: "TRUE"
            tag: "latest"
            config: "container_http_server.json"
          - name: "WasmEdge 0.9.1, Crun 1.4.5, ZH"
            latest: false
            wasmedge: "0.9.1"
            crun: "1.4.5"
            zh: "TRUE"
            tag: "compat"
            config: "container_http_server_compat.json"
          - name: "WasmEdge 0.10.0, Crun 1.5, ZH"
            latest: false
            wasmedge: "0.10.0"
            crun: "1.5"
            zh: "TRUE"
            tag: "latest"
            config: "container_http_server.json"
    runs-on: ubuntu-20.04
    name: ${{ matrix.name }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install apt-get packages
        run: |
          sudo ACCEPT_EULA=Y apt-get update
          sudo ACCEPT_EULA=Y apt-get upgrade
          sudo ACCEPT_EULA=Y apt-get install git wget

      - name: Install CRI-O and crun (specified version)
        if: ${{ ! matrix.latest }}
        env:
          WASMEDGE_VERSION: ${{ matrix.wasmedge }}
          CRUN_VERSION: ${{ matrix.crun }}
          ZH: ${{ matrix.zh }}
        run: |
          bash crio/install.sh --wasmedge=$WASMEDGE_VERSION --crun=$CRUN_VERSION --zh=$ZH

      - name: Install CRI-O and crun (latest version)
        if: ${{ matrix.latest }}
        env:
          ZH: ${{ matrix.zh }}
        run: |
          bash crio/install.sh --zh=$ZH

      - name: Run demo in CRI-O
        env:
          TAG: ${{ matrix.tag }}
          CONFIG: ${{ matrix.config }}
        run: |
          bash crio/http_server/http_server_application.sh --tag=$TAG --config=$CONFIG > dump.log 2>&1

      - name: Display crun and wasmedge version
        run: |
          crun --version
          wasmedge --version

      - name: Dump the log of execution
        run: |
          cat dump.log

      - name: Check the result
        run: |
          if grep -q "echo: name=WasmEdge" dump.log; then
            echo -e "Execution Success!"
          else
            echo -e "Execution Fail! Please check the above log for details"
            exit 1
          fi
