name: k8s-crio http server

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
  schedule:
    - cron: "0 0 */1 * *"

jobs:
  k8s_crio_server:
    strategy:
      fail-fast: false
      matrix:
        crun: ["1.15"]
        wasmedge: ["0.13.5", "0.14.0"]
        latest: [false]
        config: ["k8s-http_server.yaml"]
        include:
          - name: "WasmEdge latest release, Crun master"
            latest: true
            wasmedge: "latest"
            crun: "latest"
            config: "k8s-http_server.yaml"
            variant: "compat-smart"
    runs-on: ubuntu-20.04
    name: WasmEdge:${{ matrix.wasmedge }},crun:${{ matrix.crun }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install apt-get packages
        run: |
          sudo ACCEPT_EULA=Y apt-get update
          sudo ACCEPT_EULA=Y apt-get upgrade
          sudo ACCEPT_EULA=Y apt-get install git wget

      - name: Install CRI-O and crun (specified version)
        if: ${{ ! matrix.latest }}
        env:
          WASMEDGE_VERSION: ${{ matrix.wasmedge }}
          CRUN_VERSION: ${{ matrix.crun }}
        run: |
          bash crio/install.sh --wasmedge=$WASMEDGE_VERSION --crun=$CRUN_VERSION

      - name: Install CRI-O and crun (latest version)
        if: ${{ matrix.latest }}
        run: |
          bash crio/install.sh

      - name: Installing and starting k8s
        run: |
          bash kubernetes_crio/install.sh  > k8s.log 2>&1

      - name: Sleep for 1200s
        run: sleep 1200s
        shell: bash

      - name: Dump the log of k8s setup
        run: |
          cat k8s.log

      - name: Run WasmEdge in k8s
        continue-on-error: true
        env:
          CONFIG: ${{ matrix.config }}
        run: |
          bash kubernetes_crio/http_server/http_server_application.sh --config=$CONFIG > dump.log 2>&1

      - name: Display crun and wasmedge version
        run: |
          crun --version
          wasmedge --version

      - name: Dump the log of execution
        run: |
          cat dump.log

      - name: Check the result
        run: |
          if grep -q "echo: name=WasmEdge" dump.log; then
            echo -e "Execution Success!"
          else
            echo -e "Execution Fail! Please check the above log for details"
            exit 1
          fi
